### ISSUE TITLE
Listen on Unix Domain Sockets

### ISSUE THREAD

**Issue by eirnym** [ravenexp/crates-io-proxy#5]
Thank your for your small and robust server. 

I'd like to put the server behind nginx and it's faster and easier to configure using unix domain sockets. 

The only thing is missing is a UDS support in this server.

**Comment by ravenexp** [comment]
`tiny-http` has added support for Unix stream sockets recently, so I think it's doable. I'll add a new command line flag to make it listen on Unix sockets.

**Comment by eirnym** [comment]
Thank you for a quick response with a possibility to make it
